import { SectionDefinition } from "../../dynamic-form/types/form.types";
import { formulirKartuKeluargaSchema } from "../../schemas/layanan-kependudukan/formulir-kartu-keluarga.schema";
import { SubmitSchema } from "../../schemas/submit-schema";

export const formulirKartukeluargaSchemaWithSubmit = formulirKartuKeluargaSchema.merge(SubmitSchema);
export { formulirKartuKeluargaSchema };

/* ---- Shared options ---- */

const optionsGelar = [
  {
    label: "Tidak Ada Gelar",
    value: "-",
  },
  {
    label: "Gelar Akademis",
    value: "akademis",
  },
  {
    label: "Gelar Kebangsawanan",
    value: "kebangsawanan",
  },
  {
    label: "Gelar Keagamaan",
    value: "keagamaan",
  },
];

const optionsJenisKelamin = [
  { label: "Laki-laki", value: "laki-laki" },
  { label: "Perempuan", value: "perempuan" },
];

const optionsAgama = [
  { label: "Islam",    value: "islam"    },
  { label: "Kristen",  value: "kristen"  },
  { label: "Katolik",  value: "katolik"  },
  { label: "Hindu",    value: "hindu"    },
  { label: "Buddha",   value: "buddha"   },
  { label: "Konghucu", value: "konghucu" },
  { label: "Kepercayaan terhadap Tuhan Yang Maha Esa", value: "kepercayaan-terhadap-tuhan-yang-maha-esa" },
];

const optionsGolonganDarah = [
  { label: "A",         value: "a"         },
  { label: "B",         value: "b"         },
  { label: "AB",        value: "ab"        },
  { label: "O",         value: "o"         },
  { label: "A+",        value: "a+"        },
  { label: "B+",        value: "b+"        },
  { label: "B-",        value: "b-"        },
  { label: "AB+",       value: "ab+"       },
  { label: "AB-",       value: "ab-"       },
  { label: "O+",        value: "o+"        },
  { label: "O-",        value: "o-"        },
  { label: "Tidak Tahu", value: "tidak-tahu" },
];

const optionsStatusPerkawinan = [
  { label: "Belum Kawin", value: "belum-kawin"  },
  { label: "Kawin",       value: "kawin"        },
  { label: "Cerai Hidup", value: "cerai-hidup"  },
  { label: "Cerai Mati",  value: "cerai-mati"   },
];

const optionsHubunganKeluarga = [
  { label: "Kepala Keluarga", value: "kepala-keluarga" },
  { label: "Suami",           value: "suami"           },
  { label: "Istri",           value: "istri"           },
  { label: "Anak",            value: "anak"            },
  { label: "Menantu",         value: "menantu"         },
  { label: "Cucu",            value: "cucu"            },
  { label: "Orang Tua",       value: "orang-tua"       },
  { label: "Mertua",          value: "mertua"          },
  { label: "Famili",          value: "famili"          },
  { label: "Pembantu",        value: "pembantu"        },
  { label: "Lainnya",         value: "lainnya"         },
];

const optionsPenyandangCacat = [
  { label: "Cacat Fisik",          value: "cacat-fisik"          },
  { label: "Cacat Netra/Buta",     value: "cacat-netra"          },
  { label: "Cacat Rungu/Wicara",   value: "cacat-rungu-wicara"   },
  { label: "Cacat Mental/Jiwa",    value: "cacat-mental"         },
  { label: "Cacat Fisik & Mental", value: "cacat-fisik-mental"   },
  { label: "Cacat Lainnya",        value: "cacat-lainnya"        },
];

const optionsPendidikan = [
  { label: "Tidak/Belum Sekolah",             value: "tidak-belum-sekolah" },
  { label: "Belum Tamat SD/Sederajat",        value: "belum-tamat-sd"      },
  { label: "Tamat SD/Sederajat",              value: "tamat-sd"            },
  { label: "SLTP/Sederajat",                  value: "sltp"                },
  { label: "SLTA/Sederajat",                  value: "slta"                },
  { label: "Diploma I/II",                    value: "diploma-1-2"         },
  { label: "Akademi/Diploma III/Sarjana Muda", value: "diploma-3"          },
  { label: "Diploma IV/Strata I",             value: "diploma-4-s1"        },
  { label: "Strata II",                       value: "s2"                  },
  { label: "Strata III",                      value: "s3"                  },
];

const optionsPekerjaan = [
  { label: "Belum/Tidak Bekerja",     value: "belum-tidak-bekerja"    },
  { label: "Mengurus Rumah Tangga",   value: "mengurus-rumah-tangga"  },
  { label: "Pelajar/Mahasiswa",       value: "pelajar-mahasiswa"      },
  { label: "Pensiunan",               value: "pensiunan"              },
  { label: "Pegawai Negeri Sipil (PNS)",    value: "pns"                    },
  { label: "Tentara Nasional Indonesia (TNI)",    value: "tni"                    },
  { label: "Kepolisian RI (POLRI)",    value: "polri"                    },
  { label: "Perdagangan",    value: "perdagangan"                    },
  { label: "Petani/Pekebun",    value: "petani-pekebun"                    },
  { label: "Peternak",    value: "peternak"                    },
  { label: "Nelayan/Perikanan",    value: "nelayan-perikanan"                    },
  { label: "Industri",    value: "industri"                    },
  { label: "Konstruksi",    value: "konstruksi"                    },
  { label: "Transportasi",    value: "transportasi"                    },
  { label: "Karyawan Swasta",    value: "karyawan-swasta"                    },
  { label: "Karyawan BUMN",    value: "karyawan-bumn"                    },
  { label: "Karyawan BUMD",    value: "karyawan-bumd"                    },
  { label: "Karyawan Honorer",    value: "karyawan-honorer"                    },
  { label: "Buruh Harian Lepas",    value: "buruh-harian-lepas"                    },
  { label: "Buruh Tani/Perkebunan",    value: "buruh-tani-perkebunan"                    },
  { label: "Buruh Nelayan/Perikanan",    value: "buruh-nelayan-perikanan"                    },
  { label: "Buruh Peternakan",    value: "buruh-peternakan"                    },
  { label: "Pembantu Rumah Tangga",    value: "pembantu-rumah-tangga"                    },
  { label: "Tukang Cukur",    value: "tukang-cukur"                    },
  { label: "Tukang Listrik",    value: "tukang-listrik"                    },
  { label: "Tukang Batu",    value: "tukang-batu"                    },
  { label: "Tukang Kayu",    value: "tukang-kayu"                    },
  { label: "Tukang Sol Sepatu",    value: "tukang-sol-sepatu"                    },
  { label: "Tukang Las/Pandai Besi",    value: "tukang-las-pandai-besi"                    },
  { label: "Tukang Jahit",    value: "tukang-jahit"                    },
  { label: "Tukang Gigi",    value: "tukang-gigi"                    },
  { label: "Penata Rias",    value: "penata-rias"                    },
  { label: "Penata Busana",    value: "penata-busana"                    },
  { label: "Penata Rambut",    value: "penata-rambut"                    },
  { label: "Mekanik",                 value: "mekanik"                },
  { label: "Seniman",                 value: "seniman"                },
  { label: "Tabib",                 value: "tabib"                },
  { label: "Paraji",                 value: "Paraji"                },
  { label: "Perancang Busana",                 value: "perancang-busana"                },
  { label: "Penerjemah",                 value: "penerjemah"                },
  { label: "Imam Masjid",                 value: "imam-masjid"                },
  { label: "Pendeta",                 value: "pendeta"                },
  { label: "Pastor",                 value: "pastor"                },
  { label: "Wartawan",                 value: "wartawan"                },
  { label: "Ustadz/Mubaligh",                 value: "ustadz-mubaligh"                },
  { label: "Juru Masak",                 value: "juru-masak"                },
  { label: "Promotor Acara",                 value: "promotor-acara"                },
  { label: "Anggota DPR-RI",                 value: "anggota-dpr-ri"                },
  { label: "Anggota DPD",                 value: "anggota-dpd"                },
  { label: "Anggota BPK",                 value: "anggota-bpk"                },
  { label: "Presiden",                 value: "presiden"                },
  { label: "Wakil Presiden",                 value: "wakil-presiden"                },
  { label: "Anggota Mahkamah Konstitusi",                 value: "anggota-mk"                },
  { label: "Anggota Kabinet/Kementrian",                 value: "anggota-kabinet-kementrian"                },
  { label: "Duta Besar",                 value: "duta-besar"                },
  { label: "Gubernur",                 value: "gubernur"                },
  { label: "Wakil Gubernur",                 value: "wakil-gubernur"                },
  { label: "Bupati",                 value: "bupati"                },
  { label: "Wakil Bupati",                 value: "wakil-bupati"                },
  { label: "Walikota",                 value: "walikota"                },
  { label: "Wakil Walikota",                 value: "wakil-walikota"                },
  { label: "Anggota DPRD Provinsi",                 value: "anggota-dprd-provinsi"                },
  { label: "Anggota DPRD Kab./Kota",                 value: "anggota-dprd-kab-kota"                },
  { label: "Dosen",                 value: "dosen"                },
  { label: "Guru",                 value: "guru"                },
  { label: "Pilot",                 value: "pilot"                },
  { label: "Pengacara",                 value: "pengacara"                },
  { label: "Notaris",                 value: "notaris"                },
  { label: "Arsitek",                 value: "arsitek"                },
  { label: "Akuntan",                 value: "akuntan"                },
  { label: "Konsultan",                 value: "konsultan"                },
  { label: "Dokter",                 value: "dokter"                },
  { label: "Bidan",                 value: "bidan"                },
  { label: "Perawat",                 value: "perawat"                },
  { label: "Apoteker",                 value: "Apoteker"                },
  { label: "Psikiater/Psikolog",                 value: "psikiater-psikolog"                },
  { label: "Penyiar Televisi",                 value: "penyiar-televisi"                },
  { label: "Penyiar Radio",                 value: "penyiar-radio"                },
  { label: "Pelaut",                 value: "pelaut"                },
  { label: "Peneliti",                 value: "peneliti"                },
  { label: "Sopir",                 value: "Pialang"                },
  { label: "Paranormal",                 value: "paranormal"                },
  { label: "Pedagang",                 value: "pedangang"                },
  { label: "Perangkat Desa",                 value: "perangkat-desa"                },
  { label: "Kepala Desa",                 value: "kepala-desa"                },
  { label: "Biarawati",                 value: "biarawati"                },
  { label: "Wiraswasta",                 value: "wiraswasta"                },
  { label: "Lainnya",                 value: "lainnya"                },
];

const optionsAdaTidak = [
  { label: "Ada",      value: "ada"      },
  { label: "Tidak Ada", value: "tidak-ada" },
];

/* ---- Sections ---- */

export const formulirKartuKeluargaSections: SectionDefinition[] = [
  {
    title: "Data Kepala Keluarga",
    fields: [
      { name: "nama_kepala_keluarga", label: "Nama Kepala Keluarga", type: "text",     required: true },
      { name: "nomor_telepon",        label: "Nomor Telepon",        type: "text",     required: true, placeholder: "Contoh: 08123456789", numericOnly: true },
      { name: "alamat",               label: "Alamat",               type: "textarea", required: true, rows: 3 },
      { name: "rt",                   label: "RT",                   type: "text",     required: true, placeholder: "Contoh: 001", numericOnly: true },
      { name: "rw",                   label: "RW",                   type: "text",     required: true, placeholder: "Contoh: 002", numericOnly: true },
      { name: "kode_pos",             label: "Kode Pos",             type: "text",     required: true, placeholder: "Contoh: 50271", numericOnly: true },
    ],
  },
  {
    title: "Data Anggota Keluarga",
    fields: [
      {
        name:        "anggota_keluarga",
        label:       "Daftar Anggota Keluarga",
        type:        "array",
        required:    true,
        layout:      "card",
        defaultItem: {
          nama_lengkap:             "",
          jenis_gelar:              "",   
          gelar:                    "",
          no_ktp:                   "",
          alamat_sebelumnya:        "",
          nomor_paspor:             "",
          tanggal_berakhir_paspor:  "",
          jenis_kelamin:            "",
          tempat_lahir:             "",
          tanggal_lahir:            "",
          umur:                     "",
          akta_lahir:               "",
          nomor_akta_kelahiran:     "",
          golongan_darah:           "",
          agama:                    "",
          status_perkawinan:        "",
          akta_perkawinan:          undefined,
          nomor_akta_perkawinan:    "",
          tanggal_perkawinan:       "",
          akta_perceraian:          undefined,
          nomor_akta_perceraian:    "",
          tanggal_perceraian:       "",
          status_hubungan_keluarga: "",
          kelainan_fisik_mental:    "",
          penyandang_cacat:         undefined,
          pendidikan_terakhir:      "",
          pekerjaan:                "",
          pekerjaan_lainnya:        "",
          nik_ibu:                  "",
          nama_ibu:                 "",
          nik_ayah:                 "",
          nama_ayah:                "",
        },
        columns: [
          /* 1 */  { name: "nama_lengkap",   label: "Nama Lengkap",    type: "text",   placeholder: "Masukkan nama lengkap sesuai KTP" },
          /* 2 */  {
                      name: "jenis_gelar",
                      label: "Jenis Gelar",
                      type: "select",
                      options: optionsGelar,
                    },
                    {
                      name: "gelar",
                      label: "Gelar",
                      type: "text",
                      placeholder: "Masukkan gelar sesuai jenis gelar yang dipilih",
                      dependsOn: {
                        field: "jenis_gelar",
                        value: [
                          "akademis",
                          "kebangsawanan",
                          "keagamaan",
                        ],
                      },
                    },
          /* 3 */  { name: "no_ktp",         label: "Nomor KTP",       type: "text",   placeholder: "Masukkan 16 digit nomor KTP", numericOnly: true },
          /* 4 */  { name: "alamat_sebelumnya", label: "Alamat Sebelumnya (Opsional)", type: "text", placeholder: "Isi jika pernah tinggal di alamat lain" },
          /* 5 */  { name: "nomor_paspor",   label: "Nomor Paspor (Opsional)",    type: "text",   placeholder: "Isi jika memiliki paspor yang masih berlaku" },
          /* 6 */  { name: "tanggal_berakhir_paspor", label: "Tanggal Berakhir Paspor (Opsional)", type: "date" },
          /* 7 */  { name: "jenis_kelamin",  label: "Jenis Kelamin",   type: "select", options: optionsJenisKelamin },
          /* 8 */  { name: "tempat_lahir",   label: "Tempat Lahir",    type: "text",   placeholder: "Sesuai akta / surat kelahiran" },
          /* 9 */  { name: "tanggal_lahir",  label: "Tanggal Lahir",   type: "date" },
          /* 10 */ { name: "umur",           label: "Umur",            type: "number", min: 0,       placeholder: "Dalam tahun" },
          /* 11 */ { name: "akta_lahir",     label: "Akta Lahir / Surat Kenal Lahir", type: "select", options: optionsAdaTidak },
          /* 12 */ { name: "nomor_akta_kelahiran", label: "Nomor Akta Kelahiran", type: "text", placeholder: "Masukkan nomor akta kelahiran",
                    dependsOn: { field: "akta_lahir", value: "ada" } },
          /* 13 */ { name: "golongan_darah", label: "Golongan Darah",  type: "select", options: optionsGolonganDarah },
          /* 14 */ { name: "agama",          label: "Agama",           type: "select", options: optionsAgama },
          /* 15 */ { name: "status_perkawinan", label: "Status Perkawinan", type: "select", options: optionsStatusPerkawinan },

          /* 16 */ { name: "akta_perkawinan", label: "Akta Perkawinan / Buku Nikah", type: "select", options: optionsAdaTidak,
                    dependsOn: { field: "status_perkawinan", value: "kawin" } },
          /* 17 */ { name: "nomor_akta_perkawinan", label: "Nomor Akta Perkawinan", type: "text", placeholder: "Masukkan nomor akta perkawinan",
                    dependsOn: { field: "akta_perkawinan", value: "ada" } },
          /* 18 */ { name: "tanggal_perkawinan", label: "Tanggal Perkawinan", type: "date",
                    dependsOn: { field: "status_perkawinan", value: "kawin" } },

          /* 19 */ { name: "akta_perceraian", label: "Akta Perceraian / Surat Cerai", type: "select", options: optionsAdaTidak,
                    dependsOn: { field: "status_perkawinan", value: "cerai-hidup" } },
          /* 20 */ { name: "nomor_akta_perceraian", label: "Nomor Akta Perceraian", type: "text", placeholder: "Masukkan nomor akta perceraian",
                    dependsOn: { field: "akta_perceraian", value: "ada" } },
          /* 21 */ { name: "tanggal_perceraian", label: "Tanggal Perceraian", type: "date",
                    dependsOn: { field: "status_perkawinan", value: "cerai-hidup" } },

          /* 22 */ { name: "status_hubungan_keluarga", label: "Status Hubungan Keluarga", type: "select", options: optionsHubunganKeluarga },
          /* 23 */ { name: "kelainan_fisik_mental", label: "Kelainan Fisik dan Mental", type: "select", options: optionsAdaTidak },
          /* 24 */ { name: "penyandang_cacat", label: "Penyandang Cacat", type: "select", options: optionsPenyandangCacat,
                    dependsOn: { field: "kelainan_fisik_mental", value: "ada" } },
          /* 25 */ { name: "pendidikan_terakhir", label: "Pendidikan Terakhir", type: "select", options: optionsPendidikan },
          /* 26 */ { name: "pekerjaan",       label: "Pekerjaan",       type: "select", options: optionsPekerjaan },
                  { name: "pekerjaan_lainnya", label: "Keterangan Pekerjaan", type: "text", placeholder: "Sebutkan pekerjaan Anda",
                    dependsOn: { field: "pekerjaan", value: "lainnya" } },
          /* 27 */ { name: "nik_ibu",         label: "NIK Ibu",         type: "text",   placeholder: "Masukkan 16 digit NIK ibu", numericOnly: true },
          /* 28 */ { name: "nama_ibu",        label: "Nama Lengkap Ibu", type: "text",  placeholder: "Masukkan nama lengkap ibu" },
          /* 29 */ { name: "nik_ayah",        label: "NIK Ayah",        type: "text",   placeholder: "Masukkan 16 digit NIK ayah", numericOnly: true },
          /* 30 */ { name: "nama_ayah",       label: "Nama Lengkap Ayah", type: "text", placeholder: "Masukkan nama lengkap ayah" },
        ],
      },
    ],
  },
  {
    title: "Isian Lain",
    fields: [
      { name: "nama_ketua_rt", label: "Nama Ketua RT", type: "text", required: true },
      { name: "nama_ketua_rw", label: "Nama Ketua RW", type: "text", required: true },
    ],
  },
  {
    title:  "Upload Dokumen",
    fields: [],
  },
  {
    title: "Kirim Pengajuan",
    fields: [],
  },
];